listening-port=3478
listening-ip=127.0.0.1
external-ip=127.0.0.1
fingerprint
no-tls
no-dtls
user=samgaawaa:1234
realm=test
lt-cred-mech
allow-loopback-peers
cli-password=testcli123
log-file=/tmp/turnserver.log
Verbose
